//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public int classId { get; set; }
        public string className { get; set; }
        public string classCoach { get; set; }
        public string classDate { get; set; }
        public string classLocation { get; set; }
        public int User_userId { get; set; }
    
        public virtual User User { get; set; }
    }
}
